[tool.poetry]
name = "kuku"
version = "0.1.0"
description = ""
authors = ["matej smycka <matejsmycka@gmail.cz>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "<3.13,>=3.8"
tk = "^0.1.0"
pyinstaller = "^6.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
